package generator

import (
	"fmt"
	"github.com/dave/jennifer/jen"
	"github.com/jinzhu/inflection"
	"github.com/ycoe/gorm-generator/helper"
	"os"
	"strings"
)

/**
package dao

import model "finance/model"

type AccountDao struct {
	dao *Dao
}

func (account *AccountDao) Create (entity *model.Account) (uint, error) {
	result := account.dao.client.Table("accounts").Create(entity)
	return entity.ID, result.Error
}
*/
func GenerateDao(orgTableName string, appId, tableName, dir, idType string) {
	index := strings.LastIndex(dir, "/")
	daoPackage := dir[index+1 : len(dir)]
	f := jen.NewFile(daoPackage)
	f.HeaderComment("Code generated by model-generator.")
	f.ImportAlias(appId+"/model", "model")
	f.ImportAlias(appId+"/proto", appId)
	f.ImportAlias("time", "time")

	genGetEntityDao(f, orgTableName, tableName)
	genEntityDaoStruct(f, tableName)
	genCreateFun(f, appId, tableName, idType)
	genGetFun(f, appId, tableName, idType)

	_ = os.MkdirAll(dir, os.ModePerm)
	fileName := dir + "/" + inflection.Singular(tableName) + ".dao.go"
	if err := f.Save(fileName); err != nil {
		fmt.Println(err.Error())
	}

	fmt.Println(fileName)
}

/**
func GetAccountDao() *AccountDao {
	err := GetDao().Ping()
	if err != nil {
		logger.Error(err)
	}
	table := GetDao().client.Table("finance_account")
	return &AccountDao{
		db: table,
	}
}
*/
func genGetEntityDao(f *jen.File, orgTableName string, tableName string) {
	tableDaoName := helper.SnakeCase2CamelCase(inflection.Singular(tableName), true) + "Dao"
	f.Func().Id("Get"+tableDaoName).Params().Id("*"+tableDaoName).Block(
		jen.Id("err").Op(":=").Id("GetDao").Call().Dot("Ping").Call(),
		jen.If(
			jen.Id("err").Op("!=").Nil().Block(
				jen.Qual("github.com/micro/go-micro/v2/logger", "Error").Call(
					jen.Id("err"),
				),
			),
		),

		jen.Id("table").Op(":=").Id("GetDao").Call().Dot("client").Dot("Table").Call(
			jen.Lit(orgTableName),
		),
		jen.Return(
			jen.Id("&"+tableDaoName).Values(
				jen.Dict{
					jen.Id("db"): jen.Id("table"),
				},
			),
		),
	)
}

/**
type AccountDao struct {
	db *gorm.DB
}
*/
func genEntityDaoStruct(f *jen.File, tableName string) {
	tableEntityDaoName := helper.SnakeCase2CamelCase(inflection.Singular(tableName), true) + "Dao"
	f.Type().Id(tableEntityDaoName).Struct(
		jen.Id("db").Id("*").Qual("gorm.io/gorm", "DB"),
	)
}

/**
//通过ID获取
func (d *UserFundDao) Get(id int32) (userFund model.UserFund, err error) {
	err = d.db.First(&userFund, id).Error
	return
}
*/
func genGetFun(f *jen.File, appId, tableName, idType string) {
	entityName := helper.SnakeCase2CamelCase(inflection.Singular(tableName), true)
	entityVarName := helper.SnakeCase2CamelCase(inflection.Singular(tableName), false)
	entityDaoName := entityName + "Dao"
	f.Comment("通过ID获取").Line().Func().Params(
		jen.Id("d").Id("*"+entityDaoName),
	).Id("GetById").Params(
		jen.Id("id").Id(idType),
	).Params(
		jen.Id(entityVarName).Id("model").Dot(entityName),
		jen.Id("err").Id("error"),
	).Block(
		jen.Id("err").Op("=").Id("d").Dot("db").Dot("First").Call(
			jen.Id("&").Id(entityVarName),
			jen.Id("id"),
		).Dot("Error"),
		jen.Return(),
	)
}

/**
func (dao *AccountDao) Create(entity *model.Account) (uint, error) {
	result := d.db.Create(entity)
	return entity.ID, result.Error
}
*/
func genCreateFun(f *jen.File, appId, tableName, idType string) {
	entityName := helper.SnakeCase2CamelCase(inflection.Singular(tableName), true)
	entityDaoName := entityName + "Dao"

	f.Comment("创建").Line().Func().Params(
		jen.Id("d").Id("*"+entityDaoName),
	).Id("Create").Params(
		jen.Id("entity").Id("*").Qual(appId+"/model", entityName),
	).Params(
		jen.Id(idType),
		jen.Id("error"),
	).Block(
		jen.Id("result").Op(":=").Id("d").Dot("db").Dot("Create").Call(
			jen.Id("entity"),
		),
		jen.Return(
			jen.Id("entity").Dot("ID"),
			jen.Id("result").Dot("Error"),
		),
	).Line()
}
