package generator

import (
	"fmt"
	"github.com/dave/jennifer/jen"
	"github.com/jinzhu/inflection"
	"github.com/ycoe/gorm-generator/helper"
	"os"
	"strings"
)

func GenerateModel(tableName string, columns []map[string]string, dir string) string {
	index := strings.LastIndex(dir, "/")
	daoPackage := dir[index+1 : len(dir)]
	var codes []jen.Code
	idType := ""
	for i, col := range columns {
		t := col["Type"]
		column := col["Field"]
		var st *jen.Statement
		st = jen.Id(helper.SnakeCase2CamelCase(column, true))
		columnType := getCol(st, t)
		if idType == "" && i == 0 {
			idType = columnType
		}
		st.Tag(map[string]string{"json": column})
		st.Comment(col["Comment"])
		codes = append(codes, st)
	}
	f := jen.NewFile(daoPackage)
	f.HeaderComment("Code generated by model-generator. DO NOT EDIT.")
	f.ImportAlias("time", "time")
	f.Type().Id(helper.SnakeCase2CamelCase(inflection.Singular(tableName), true)).Struct(codes...)
	_ = os.MkdirAll(dir, os.ModePerm)
	fileName := dir + "/" + inflection.Singular(tableName) + ".go"
	fmt.Println(fileName)
	if err := f.Save(fileName); err != nil {
		fmt.Println(err.Error())
	}
	return idType
}

func getCol(st *jen.Statement, t string) string {
	prefix := strings.Split(t, "(")[0]
	switch prefix {
	case "int", "tinyint", "smallint", "bigint", "mediumint":
		st.Int32()
		return "int32"
	case "float", "decimal":
		st.Float32()
		return "float32"
	case "date", "time", "timestamp", "year", "datetime":
		st.Id("*").Qual("time", "Time")
		return "time.Time"
	default:
		st.String()
		return "string"
	}
}
